Delta_0: 0.1
K_candidates: 16
alpha_parab: 0.3
beta_parab: 1.5
eps_bg_list:
- 6.0
- 9.0
eps_bg_max: 12.0
k_interp: 19
kappa_0: 1.0
lattice_types:
- square
- hex
n_theta: 3
num_bands: 8
output_dir: runs
r_over_a_list:
- 0.25
- 0.35
resolution: 32
run_name: phase0_real_run
target_bands:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
theta_range:
- 1.0
- 2.5
use_simplified_model: false
v_0: 1.0
w_contrast: 0.05
w_flat: 0.35
w_gap: 0.25
w_parab: 0.2
w_vg: 0.15
