Delta_0: 0.12
K_candidates: 16
alpha_parab: 0.3
beta_parab: 1.5
eps_bg_list:
- 2.0
- 3.0
- 4.0
- 5.0
- 6.0
- 7.0
- 8.0
- 9.0
eps_bg_max: 12.0
k_interp: 19
kappa_0: 1.0
lattice_types:
- square
- hex
max_workers: 1
num_bands: 10
output_dir: runs
parab_span_ref: 0.45
phase0_enable_optimizer: false
phase0_opt_eps_bounds:
- 2.0
- 12.0
phase0_opt_maxiter: 12
phase0_opt_polish: false
phase0_opt_popsize: 6
phase0_opt_r_bounds:
- 0.18
- 0.4
phase0_opt_tol: 0.001
quiet_mpb: true
r_over_a_list:
- 0.2
- 0.25
- 0.3
- 0.35
resolution: 32
run_name: phase0_real_run
symmetry_ref: 1.0
target_bands:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
use_simplified_model: false
v_0: 1.0
vg_ref: 0.08
w_flat: 0.7
w_gap: 1.1
w_linear: 0.8
w_parab: 0.45
w_sym: 0.6
w_vg: 0.35
