Delta_0: 0.12
K_candidates: 16
alpha_parab: 0.3
band_library_path: /home/renlephy/msl/research/band_diagram_scan/data/band_library.h5
band_library_scan_id: square_hex_eps_r_v1
beta_parab: 1.5
eps_bg_max: 9.8
eps_bg_min: 2.0
eps_bg_scoring_max: 12.0
kappa_0: 1.0
lattice_types:
- square
- hex
output_dir: runsV2
parab_span_ref: 0.45
polarizations:
- TE
- TM
r_over_a_max: 0.3
r_over_a_min: 0.15
run_name: phase0_v2_library
symmetry_ref: 1.0
target_bands:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
use_library_parameters: true
v_0: 1.0
vg_ref: 0.08
w_flat: 0.7
w_gap: 1.1
w_linear: 0.8
w_parab: 0.45
w_sym: 0.6
w_vg: 0.35
